import { Container } from "@mui/material"
import Head from "next/head"
import { ReactNode } from "react"
import Footer from "./Footer"
import Nav from "./Nav"

type Props = {
  children?: ReactNode
  title?: string
  home?: boolean
}

const Layout = ({ children, title, home }: Props) => {
  return (
    <>
      <Head>
        <title>{title ?? "Property Application"}</title>
        <meta charSet="utf-8" />
        <meta name="viewport" content="initial-scale=1.0, width=device-width" />
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="layout-wrap">
        <Nav />
        <Container>
          <main>{children}</main>
        </Container>
      </div>
      {/* <Footer /> */}
    </>
  )
}

export default Layout